# Generated by Django 4.1.6 on 2023-02-05 09:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
