# Generated by Django 4.1.6 on 2023-02-09 02:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_skills_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
